local assets = {
	["images/projectiles/laser-bullet.png"] = "rbxasset://.asphalt-space-game/images/projectiles/laser-bullet.png",
	["images/ui/background-round.png"] = "rbxasset://.asphalt-space-game/images/ui/background-round.png",
	["images/ui/border-round.png"] = "rbxasset://.asphalt-space-game/images/ui/border-round.png",
	["images/ui/border-single.png"] = "rbxasset://.asphalt-space-game/images/ui/border-single.png",
}

return assets